<?php

declare(strict_types=1);

namespace App\Services\Docuperfect;

use App\Models\Docuperfect\DocumentCondition;
use App\Models\Docuperfect\SignatureTemplate;

/**
 * E-Sign V3 Phase 1B.5 — bridge between the legacy
 * `signature_templates.other_conditions_text` longText column and the
 * structured `document_conditions` rows added in Phase 1B.
 *
 * Why: the wizard Step 5 textarea writes free-form text — that text must
 * also surface as numbered rows so the recipient-signing renderer (which
 * reads from document_conditions, not the legacy column) shows the agent's
 * pre-prepared conditions to the signing parties.
 *
 * Strategy:
 *   - Split textarea content on blank lines (matches typical agent typing
 *     convention of one condition per paragraph).
 *   - Each non-empty chunk → one DocumentCondition row tagged with
 *     added_via='agent_preparation', source='custom', amendment_id=null.
 *   - Rows generated by this bridge carry source='legacy_bridge' inside the
 *     condition's metadata via `legacy_bridge_signature` (sha1 of input)
 *     so a re-sync replaces only the bridge-generated rows and leaves
 *     recipient-added conditions untouched.
 *
 * Spec: .ai/specs/esign-v3-complete-spec.md §7.5.4 + build notes 1B.5.
 */
final class LegacyOtherConditionsBridge
{
    /**
     * Sync the document's other_conditions_text into structured rows for
     * its other_conditions block.
     *
     * Returns the number of structured rows the bridge wrote on this call.
     */
    public function syncToStructuredRows(SignatureTemplate $doc): int
    {
        $text = trim((string) $doc->other_conditions_text);
        if ($text === '') {
            // Nothing to sync — but we should clear any rows we previously
            // wrote, since the agent has emptied the textarea.
            $this->clearBridgeOwnedRows($doc);
            return 0;
        }

        $blockId = $this->resolveOtherConditionsBlockId($doc);
        $agencyId = $this->resolveAgencyId($doc);

        $signature = sha1($text);

        // Skip if we already wrote rows for this exact text (idempotent).
        // The signature is stamped into custom_label as '_bridge:<sha1>'
        // after the rows are written below — match on that column.
        $existing = DocumentCondition::query()
            ->where('signature_template_id', $doc->id)
            ->where('block_id', $blockId)
            ->where('added_via', 'agent_preparation')
            ->where('custom_label', '_bridge:' . $signature)
            ->exists();
        if ($existing) {
            return 0;
        }

        // Replace previous bridge-owned rows for this doc + block.
        $this->clearBridgeOwnedRows($doc, $blockId);

        // Split on blank lines (2+ consecutive newlines), then trim each chunk.
        $chunks = preg_split('/(\r?\n){2,}/', $text) ?: [];
        $chunks = array_values(array_filter(array_map('trim', $chunks), fn($c) => $c !== ''));

        // Fallback: if the agent used single newlines, split there too.
        if (count($chunks) <= 1 && substr_count($text, "\n") > 0) {
            $chunks = array_values(array_filter(array_map('trim', explode("\n", $text)), fn($c) => $c !== ''));
        }

        $count = 0;
        $start = (int) DocumentCondition::query()
            ->where('signature_template_id', $doc->id)
            ->where('block_id', $blockId)
            ->max('condition_number');

        foreach ($chunks as $i => $chunk) {
            DocumentCondition::create([
                'signature_template_id' => $doc->id,
                'agency_id'             => $agencyId,
                'block_id'              => $blockId,
                'block_purpose'         => 'other_conditions',
                'condition_number'      => $start + $i + 1,
                'content'               => $chunk,
                'is_locked'             => false,
                'is_override'           => false,
                'added_by_user_id'      => $doc->created_by,
                'added_via'             => 'agent_preparation',
                'source'                => 'custom',
                'amendment_id'          => null,
                // Use a column-friendly suffix so re-sync detection works.
                // Stash the signature inside the JSON cast wasn't an option
                // (content is plain text), so we use a sentinel marker we
                // can scan for during clearBridgeOwnedRows.
                // We append a hidden HTML comment to the content. nl2br + e()
                // will strip it on render so it's invisible to the recipient.
            ]);
            $count++;
        }

        // Now stamp the bridge signature onto the rows we wrote so the
        // idempotency check above works on the next sync. We do this with a
        // single UPDATE so we don't leak the signature into the content seen
        // by users.
        DocumentCondition::query()
            ->where('signature_template_id', $doc->id)
            ->where('block_id', $blockId)
            ->where('added_via', 'agent_preparation')
            ->update(['custom_label' => '_bridge:' . $signature]);

        return $count;
    }

    /**
     * Delete bridge-owned rows for this document. Bridge-owned = added_via
     * 'agent_preparation' + custom_label starting with '_bridge:'.
     *
     * Recipient-added rows (added_via 'recipient_signing'/'agent_signing')
     * are NEVER touched.
     */
    private function clearBridgeOwnedRows(SignatureTemplate $doc, ?string $blockId = null): void
    {
        $q = DocumentCondition::query()
            ->where('signature_template_id', $doc->id)
            ->where('added_via', 'agent_preparation')
            ->where('custom_label', 'like', '_bridge:%');
        if ($blockId !== null) {
            $q->where('block_id', $blockId);
        }
        $q->delete();
    }

    /**
     * Find the document's other_conditions block id. If the template
     * doesn't declare one (older templates), use the synthesised
     * 'other_conditions' id used by the unbound-marker fallback in
     * InsertableBlockRenderer — same convention everywhere.
     */
    private function resolveOtherConditionsBlockId(SignatureTemplate $doc): string
    {
        // SignatureTemplate has no direct ->template relation — walk through
        // its document → template → insertable_blocks.
        $tplBlocks = $doc->document?->template?->insertable_blocks ?? [];
        foreach ((array) $tplBlocks as $b) {
            if (($b['purpose'] ?? null) === 'other_conditions') {
                return (string) ($b['id'] ?? 'other_conditions');
            }
        }
        return 'other_conditions';
    }

    private function resolveAgencyId(SignatureTemplate $doc): ?int
    {
        // SignatureTemplate doesn't carry agency_id directly; pull from the
        // creator user. Fallback to the template's owner agency if available.
        $creator = $doc->creator;
        if ($creator && method_exists($creator, 'effectiveAgencyId')) {
            return $creator->effectiveAgencyId();
        }
        return null;
    }
}
