<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LEASE AGREEMENT - RESIDENTIAL</title>
    <link href="/css/corex-document.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
<div class="corex-document-wrapper">
<div class="corex-page">

@include("docuperfect.web-templates.components.company-header")

<div class="corex-h1">LEASE AGREEMENT - RESIDENTIAL</div>
<div class="corex-h1">1. &nbsp;PARTIES </div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"> <span class="corex-field-value" data-field="lessor_full">{{ $lessor_full ?? '' }}</span> (Lessor / Landlord) </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Of (address) <span class="corex-field-value" data-field="lessor_address">{{ $lessor_address ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">ID/Passport/Registration No:  <span class="corex-field-value" data-field="lessor_id_number">{{ $lessor_id_number ?? '' }}</span></span></div>
<div class="corex-h1">AND</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><span class="corex-field-value" data-field="lessee_name_id">{{ $lessee_name_id ?? '' }}</span> (Lessee / tenant / Occupant)</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">      of (address) <span class="corex-field-value" data-field="lessee_address">{{ $lessee_address ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">ID/Passport/Registration No:   <span class="corex-field-value" data-field="lessee_id_number">{{ $lessee_id_number ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">It is agreed that, from date of occupation, the DOMICILIUM CITANDI ET EXECUTANDI will be the property address.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Please note that according to the Consumer Protection Act 68 of 2008 the following is applicable to the Lessee:</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">a)</span> <span class="corex-clause-text">If you are a Juristic Entity (Company / Trust / Closed Corporation) with assets or turnover less than R2 million per annum the CPA is applicable.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">b)</span> <span class="corex-clause-text">If you are an individual, private person leasing a property through an estate agency the CPA is applicable.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">c)</span> <span class="corex-clause-text">If the Lessor and Lessee are Juristic persons the cancellation provisions of the CPA are not applicable regardless of turnover or assets.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">d)</span> <span class="corex-clause-text">Should this lease agreement have been entered into as a result of direct marketing, the Lessee shall have 5 business days cooling off period, therefore the Landlord may continue to advertise and market the property until the 5 day period lapsed.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">e)</span> <span class="corex-clause-text">Where the CPA is applicable the lessee may give a 20 business day notice, equal to 1 (one) month at any stage during the lease.  By signing this Lease Agreement, the Lessee acknowledges that he/she is aware of the cancellation fees stipulated in this Lease Agreement.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">f)</span> <span class="corex-clause-text">Please note that no Lease Agreement may be for a period longer than 24 (twenty four) months.</span></div>
<div class="corex-h1">1. &nbsp;INTERPRETATION</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">In this Agreement, unless the context indicates otherwise, the following expressions shall have the meanings assigned to them hereunder. </span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"> 	The premises :- being </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">                <span class="corex-field-value" data-field="property_full">{{ $property_full ?? '' }}</span> (Property)</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"> 	the Rental:- being the amount referred to in 4.1 or, 5.2.2 as escalated in terms of 4.2.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text">The Estate Agent being: - The firm:- Home Finders Coastal   </span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text">  	the Deposit:- as referred to in clause 6.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.5</span> <span class="corex-clause-text">Home Finders Coastal is the Agent, not the Landlord, and can only act on the instructions of the Landlord.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.6</span> <span class="corex-clause-text">The LANDLORD remains the responsible party for any concerns, disputes or claims arising from the LEASE.</span></div>
<div class="corex-h1">3.  LETTING AND HIRING</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">3.1</span> <span class="corex-clause-text">	The Lessor hereby lets to the Lessee, who hereby hires, the Premises subject to the terms and conditions contained in this Agreement. </span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">3.2</span> <span class="corex-clause-text">	The Premises shall be personally occupied by <span class="corex-field-value" data-field="occupants">{{ $occupants ?? '' }}</span> Adults and not more than <span class="corex-field-value" data-field="kids">{{ $kids ?? '' }}</span> other persons. </span></div>
<div class="corex-h1">4.  RENTAL</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">	Delete 4.2 if not applicable. </span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">4.1</span> <span class="corex-clause-text">	The Rental shall be <span class="corex-field-value" data-field="monthly_rental">{{ $monthly_rental ?? '' }}</span>(<span class="corex-field-value" data-field="price_in_words">{{ $price_in_words ?? '' }}</span>) per month, subject to 4.2 and shall be paid monthly in advance on the 1st day of each month, free of any set-off, by means of bank/internet transfer of cash deposits into the Agency’s  banking account.  The LESSEE must ensure that the Agency receives in their account, on or before the due date, all payments due. The LESSEE must make allowance for bank transfer delays. The Agency is required to report all cash deposits over R50000 to FICA. The LESSEE acknowledges that all cash deposit fees charged by the bank will be for the account of the LESSEE.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"> The Rental shall be subject to an escalation of <span class="corex-field-value" data-field="escalation">{{ $escalation ?? '' }}</span>% (<span class="corex-field-value" data-field="escalation_alpha">{{ $escalation_alpha ?? '' }}</span>) per annum from the 1st day of <span class="corex-field-value" data-field="escalation_month">{{ $escalation_month ?? '' }}</span> each year, and the amount referred to in 4.1, escalated as aforesaid, shall then with effect from the said date constitute the Rental.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text">The LANDLORD	 or his Agent shall, on written request only provide the LESSEE with written receipt for all payments received. (Please refer the electronic invoice and payment link sent via email for your statement).</span></div>
<div class="corex-h1">5.  LEASE PERIOD</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text">The lease shall commence on <span class="corex-field-value" data-field="property_lease_start_date">{{ $property_lease_start_date ?? '' }}</span>, and shall continue thereafter until terminated by either party giving the other not more than 80(eighty) and not less than 40(forty) business days’ notice of termination.  Provided that such notice of termination-</span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.1</span> <span class="corex-clause-text">may not be given by either party to expire prior to the <span class="corex-field-value" data-field="notice_date">{{ $notice_date ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.2</span> <span class="corex-clause-text">; and</span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.3</span> <span class="corex-clause-text">shall be given only on or before the 1st day of any calendar month.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><strong>	</strong><strong>The lease shall expire at midnight </strong><strong>on </strong><span class="corex-field-value" data-field="property_lease_end_date">{{ $property_lease_end_date ?? '' }}</span><strong>, (</strong><strong>the expiry </strong><strong>date).</strong><strong>  </strong><strong>W</strong><strong>ith written consent from the</strong><strong> </strong><strong>Lessor, t</strong><strong>he</strong><strong> </strong><strong>Lessee has</strong><strong> </strong><strong>the option to renew the lease for a</strong><strong> </strong><strong>further period of </strong><span class="corex-field-value" data-field="renewal_period">{{ $renewal_period ?? '' }}</span><strong> </strong><strong>months (the renewal period), commencing on the first day</strong><strong> </strong><strong>after the expiry date, on the same terms and conditions contained in this Agreement. Provided that – </strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.2.1</span> <span class="corex-clause-text"><strong>T</strong><strong>he Lessee shall exercise this option by giving written notice to the Lessor on or before </strong><strong>two months prior to expiry date as per </strong><strong>clause</strong><strong> 5.1.1 and 5.2 above</strong><strong> failing </strong><strong>w</strong><strong>hich the option shall lapse</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text"><strong>The Lessee agrees that the Agency may erect a Let by Board outside the property for 30 days after occupation of the property by the Lessee.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text"><strong>The lease and all provisions of the Lease shall continue on a month to month basis if this lease period expires and no renewal or extension to this lease has been signed and agreed to by the Lessee, Lessor and or Agency.  Please refer to clause 17 on how the termination of a lease agreement works.</strong></span></div>
<div class="corex-h1">6.  DEPOSIT AND ELECTRICITY DEPOSIT</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>The Lessee shall within </strong>48 hours<strong>, after the Lessor has signed this Agreement pay a </strong><strong>d</strong><strong>eposit</strong><strong> equal to 1 </strong><strong>month’s</strong><strong> </strong><strong>rental to</strong><strong> the </strong><strong>Agency </strong><strong>to be kept by him in trust until</strong><strong> </strong><strong>termination of the lease.</strong><strong>  </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><strong>As and when the monthly rental payment increase in accordance with this agreement, the </strong><strong>a</strong><strong>mount of the deposit shall automatically increase in the same proportion to the increase</strong><strong> </strong><strong>in the rental as stipulated in Clause 1.2, which deposit shall be due and payable on or before the first day of the month following the month in which the increase monthly rental amount is payable.</strong><strong>	</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text"><strong>On termination of the lease, the deposit shall be refunded to the Lessee as soon as possible less any amounts	</strong><strong> </strong><strong>which the Lessor in his discretion may deduct for the payment of all amounts for which the Lessee is liable under this Agreement including but without limitation, arrear Rental, unpaid electricity and telephone accounts, the cost of repairing damage to the Premises, and/or replacing lost keys.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text"><strong>The Lessee shall not be entitled to use the deposit as rental for any month or for the last month(s) period of the lease.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.5</span> <span class="corex-clause-text"><strong>Interest earned on the </strong><strong>d</strong><strong>eposit while kept in </strong><strong>an Interest bearing account</strong><strong> accrues to the Lessee.</strong></span></div>
<div class="corex-h1">7.  ELECTRICITY</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>	</strong><strong>Municipality</strong><strong> electricity account to remain in </strong><strong>the name of the </strong><strong>Lessor. </strong><strong>The m</strong><strong>onthly statements to </strong><strong>b</strong><strong>e</strong><strong> sent to the Lessee</strong><strong> by the Lessor</strong><strong> </strong><strong>for </strong><strong>settlement:</strong><strong>	</strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number"></span> <span class="corex-clause-text"><strong>D</strong><strong>irect se</strong><strong>ttlement to the Agency</strong><strong>    </strong></span></div>
<div class="corex-h1">8.  ADDITIONAL PAYMENTS BY LESSEE</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>The costs of drawing up this Lease Agreement and auxiliary expenses amounting to </strong>R1200.00<strong> (</strong><strong>One Thousand Two Hundred</strong><strong> Rand</strong><strong> only) </strong><strong>inclu</strong><strong>sive of</strong><strong> V</strong><strong>at thereon, payable together with the deposit as per clause </strong><strong>6</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>The</strong><strong> Lessee shall</strong><strong> on demand pay to the Lessor </strong><strong>all legal costs, </strong><strong>as between</strong><strong> attorney and client, incurred by the Lessor in respect </strong><strong>of any</strong><strong> legal steps taken by him against the Lessee to enforce any of the Lessee’s obligations in terms of this Agreement.</strong><strong>  E</strong><strong>xcept</strong><strong> insofar as they are included in any levy payable by the Lessor in terms </strong><strong>of clause</strong><strong> 10</strong><strong>, the</strong><strong> </strong><strong>Lessee shall from the date of commencement of this lease promptly pay for</strong><strong> – </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number"></span> <span class="corex-clause-text"><strong>A</strong><strong>ll electricity; </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number"></span> <span class="corex-clause-text"><strong>Any</strong><strong> other fees payable in respect of services rendered to the Premises during the </strong><strong>p</strong><strong>eriod of the lease. </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">8.2</span> <span class="corex-clause-text"><strong>8</strong><strong>.2</strong><strong>	</strong><strong>	</strong><strong>I</strong><strong>n the event of the Lessee failing to make payment of any of the a foregoing, the Lessor shall have the right without prejudice to his other rights in law or under this Agreement to effect payment himself and recover the amount/s so expended from the Lessee.</strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>8</strong><strong>.</strong><strong>3</strong><strong>If rental is received late, as specified in Clause 	</strong><strong>4</strong><strong> above, more than three times during the Le</strong><strong>ase Agreement period, the Lessee</strong><strong> shall be liable to pay a further 50% (fifty percent) of the existing Monthly Rental as an additional deposit.</strong></span></div>
<div class="corex-h1">9. &nbsp;LESSEE’S OBLIGATIONS</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>The Lessee acknowledges that he shall</strong><strong>: -</strong><strong> Maintain the whole interior of the premises and undertakes to deliver the premises to the landlord at termination of this lease in the same good order and condition as received.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.1</span> <span class="corex-clause-text"><strong>Replace at his expense all light bulbs, fluorescent tubes, fluorescent s</strong><strong>tarters, tap washers and water </strong><strong>ballasts on the PREMISES as and when necessary.</strong><strong> </strong><strong> All repairs effected shall be to a level of quality acceptable to the LANDLORD;</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.2</span> <span class="corex-clause-text"><strong>Ensure that neither he nor any other person shall mark, paint or drive nails or affix screws or hooks</strong><strong> </strong><strong>which would, in any way, deface or damage the doors, walls, floors, or any part of the PREMISES,</strong><strong> </strong><strong>without the express prior written permission of the LANDLORD, which shall not be unreasonably withheld.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.3</span> <span class="corex-clause-text"><strong>Keep and maintain all sewerage systems and waste/water/ down pipes, guttering, and drains free from obstruction and blockages and shall remove, at his cost, any blockages or obstructions.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.4</span> <span class="corex-clause-text"><strong>Clean all curtains, blinds, carpets and other floor coverings and tiles regularly, it being recorded</strong><strong> </strong><strong>that these items shall be replaced complet</strong><strong>ely at the expense of the Lessee</strong><strong> should they be </strong><strong>d</strong><strong>amaged by the </strong><strong>Le</strong><strong>s</strong><strong>see</strong><strong>, or deteriorate in a manner not comm</strong><strong>ensurate with ordinary wear and t</strong><strong>ear. It is recorded that all curtains, blinds and carpets on the PR</strong><strong>EMISES are to be professionally </strong><strong>steam cleaned by the Lessee</strong><strong> prior to his vacation of the PREMISES and proof of such to be handed to the </strong><strong>Agency or the </strong><strong>LANDLORD.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.5</span> <span class="corex-clause-text"><strong>If applicable, keep the grounds of the PREMISES in a clean and tidy condition</strong><strong>, free from all litter, and keep hedges and lawns trimmed, and the flowerbeds neat, tidy and free from weeds and the entire garden watered regularly.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.6</span> <span class="corex-clause-text"><strong>If applicable, maintain the swimming pool, its </strong><strong>filtration plant</strong><strong> and keep all pool cleaning</strong><strong> </strong><strong>equipment in good working order and free from all obstructi</strong><strong>on and contamination. The Lessee </strong><strong>s</strong><strong>hall pay for and administer such chemicals as are necessary for the proper maintenance of the pool,</strong><strong> </strong><strong>including the proper and frequent filtration of the water.</strong><strong> The </strong><strong>LANDLORD</strong><strong> to arrange a pool net as per the Municipal </strong><strong>Bylaw</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.7</span> <span class="corex-clause-text"><strong>The Lessee is responsible for the upkeep of the garden including the trimming of hedges and trees, but will not </strong><strong>c</strong><strong>ut or remove trees or plants or effect any alterations to the garden</strong><strong> without written consent from the Landlord</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.8</span> <span class="corex-clause-text"><strong>Should the LANDLORD agree to allow pets, subject to the rules of the Bodies mentioned above, the LANDLORD gives permission to only the following type and number of pets on the PREMISES:</strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">             <span class="corex-field-value" data-field="what_pets_are_allowed">{{ $what_pets_are_allowed ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.9</span> <span class="corex-clause-text"><strong>Keep the electrical system in good working order and condition, fair wear and tear excepted.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.10</span> <span class="corex-clause-text"><strong>A</strong><strong>ll goods brought onto the premises by the Lessee shall be at the sole risk of the Lessee.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.11</span> <span class="corex-clause-text"><strong>The Lessor shall not be liable for any loss sustained by the Lessee by reason of any burglary</strong><strong> o</strong><strong>f or fire on the Premises or for any damage suffered by the Lessee as the result of any act or </strong><strong>o</strong><strong>mission on the part of</strong><strong> the Lessor </strong><strong>as a result of any defect in the</strong><strong> </strong><strong>Premises.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">9.12</span> <span class="corex-clause-text"><strong>T</strong><strong>he Lessee shall allow the Lessor to inspect the premises at all reasonable times after </strong><strong>g</strong><strong>iving 24 (twenty four) </strong><strong>hours’ notice</strong><strong> to the Lessee.</strong></span></div>
<div class="corex-h1">10.  LESSORS OBLIGATIONS</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>The Lessor shall be liable to pay all rates and taxes/ levies payable in respect of the Premises</strong><strong> t</strong><strong>o </strong><strong>t</strong><strong>he local authority/body corporate/share block company/home owners’ association</strong><strong> </strong><strong>concerned.</strong><strong>  </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>The Lessor shall also keep the premises insured against fire and other unusual risks.</strong><strong>  </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><strong>The Lessor shall keep all external windows, doors and walls, and roofs in order, but shall not be responsible for any damages to any of the Lessee’s possessions as a result of any defect of any nature whatsoever.</strong><strong>  </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text"><strong>The Lessor shall be responsible for all maintenance repairs related to all plumbing installations, including the hot water cylinder(s) on the premises.</strong></span></div>
<div class="corex-h1">11.  PROHIBITION AGAINST SUBLETTING AND PARTING WITH POSSESSION</div>
<div class="corex-h2">The Lessee shall not –</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">11.1</span> <span class="corex-clause-text"><strong>11</strong><strong>.1</strong><strong>	</strong><strong>cede his rights or assign his obligations hereunder; or </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">11.2</span> <span class="corex-clause-text"><strong>11</strong><strong>.2</strong><strong>	</strong><strong>sublet the Premises or any portion thereof; or </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">11.3</span> <span class="corex-clause-text"><strong>11</strong><strong>.3</strong><strong>	</strong><strong>part with possession of the Premises or any portion thereof without the Lessor’s prior</strong><strong> </strong><strong>written </strong><strong>consent which, in the case of 11</strong><strong>.2 and </strong><strong>11</strong><strong>.3, shall not be unreasonably withheld. </strong></span></div>
<div class="corex-h1">12.  OCCUPATION</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>Notwithstanding any receipt given for rental or deposit paid in terms of the le</strong><strong>ase, the </strong><strong>Lessee shall have no claim for damages or other right action against the Lessor, nor be entitled to cancel this</strong><strong> </strong><strong>lease, should the Lessor be unable to give the Lessee occupation of the premises on the date of</strong><strong> </strong><strong>commencement of the lease for any reason whatsoever not attributable to willful default on the part of the Lessor, and the lessee undertake to accept occupation from</strong><strong> wh</strong><strong>atever date the Premises are available, subject to a remission of rental</strong><strong> </strong><strong>in respect of the period of non-occupation.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><strong>Should the Lessee fai</strong><strong>l to take occupation of the Premises on the date upon which the </strong><strong>P</strong><strong>remises are</strong><strong> </strong><strong>made available to him for </strong><strong>occupation;</strong><strong> the Lessor may without incurring any </strong><strong>l</strong><strong>iability whatsoever</strong><strong> </strong><strong>towards the Lessee immediately cancel this Agreement without </strong><strong>n</strong><strong>otice, whereupon the Lessee shall forfeit the Deposit paid by him while remaining liable </strong><strong>f</strong><strong>or any loss of rental or other losses sustained by the Lessor.  Provided that this clause shall not apply if the Lessor and Lessee have agreed in writing that the Lessee will not take physical occupation of the Premises on the said date.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text"><strong>In the event of the Lessee not being able to enjoy the benefi</strong><strong>cial occupation of the Premises</strong><strong> a</strong><strong>s a result of them having been materially damaged by fire, earthquakes, weather storms, </strong><strong>r</strong><strong>iot activity</strong><strong> </strong><strong>or the like and Lessor –</strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">12.3.1</span> <span class="corex-clause-text"><strong>1</strong><strong>2</strong><strong>.3.1 </strong><strong>	</strong><strong>F</strong><strong>a</strong><strong>i</strong><strong>ling within 30 days of the date of the damage to give the Lessee written notice that he</strong><strong> </strong><strong>intends to keep this lease alive, this lease shall be deemed to have been cancelled on the</strong><strong> </strong><strong>date that the damage occurred and the Lessor shall refund to the Lessee all rental paid in</strong><strong> </strong><strong>advance beyond the date of such damage; or</strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">12.3.2</span> <span class="corex-clause-text"><strong>12</strong><strong>.3.2  </strong><strong> </strong><strong>  </strong><strong>H</strong><strong>aving given notice to the Lessee as aforesaid, the Lessor shall restore the Premises to</strong><strong> </strong><strong>a tenantable condition as expeditiously as practicable and the Lessee shall be entitled to a total or</strong><strong> </strong><strong>partial remission of rental according to the extent to which and the period for which he was deprived of beneficial occupation of the Premises</strong><strong> </strong><strong>Save a</strong><strong>s</strong><strong> provided in 11.3.1 and 11.3.2 </strong><strong>the Lessee shall have no other claims whatsoever</strong><strong> </strong><strong>against the Lessor.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">12.4</span> <span class="corex-clause-text"><strong>12.4</strong><strong>  </strong><strong>	</strong><strong>The Lessee may not without the Lessor’s prior written consent which shall not be</strong><strong> </strong><strong>unreasonably withheld –</strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.1</span> <span class="corex-clause-text"><strong>A</strong><strong>llow the Premises to remain unoccupied for any period exceeding six weeks; or</strong><strong> </strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.2</span> <span class="corex-clause-text"><strong>Permit</strong><strong> or allow any person other than those persons referred to in 3.2 above to occupy the Premises or to reside therein.</strong></span></div>
<div class="corex-h1">13.  DEFECTS, INSPECTIONS AND MAINTENANCE</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>The Lessor </strong><strong>and the Lessee shall jointly inspect the Premises before the Lessee moves into the Premises. </strong><strong> After the inspection has been done </strong><strong>by the Lessee and Lessor</strong><strong> the Lessee has 7(seven) days from the commencement date as specified in clause 5 to report any other damages to the property.</strong><strong> </strong><strong> </strong><strong>Should the Lessee not attend the ingoing inspection with the</strong><strong> Lessor</strong><strong>, </strong><strong>or report any damages within the 7 (seven) </strong><strong>the Lessee agrees that there are no damages in or to the Premises.</strong><strong>  </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><strong>Any damages in or to the Premises at the ingoing inspection</strong><strong>, must be recorded on the Inspection list which shall be signed and dated by the</strong><strong> Lessee and the Landlord</strong><strong>, and attached to the Lease Agreement marked Annexure A.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text"><strong>The property is let and rented in the condition in which it is at the beginning of the Lease Agreement.  No obligations sha</strong><strong>ll rest on the Landlord</strong><strong> to repair any of the defects listed in Annexure A, unless specially specified as a special condition of lease. </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text"><strong>Should the outgoing inspection of the property be the same time as the ingoing inspection for another lessee, then the Lessee agrees to do this outgoing inspection the same time as the new Lessee’s incoming inspection. </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.5</span> <span class="corex-clause-text"><strong>At the end of the Lea</strong><strong>se Agreement, the Lessor</strong><strong> and the Lessee will jointly inspect the Premises</strong><strong> for any damages on the last day of the lease, or up to 3 days after vacating the premises.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.6</span> <span class="corex-clause-text"><strong>The Lessor may use any amount of the deposit / deposits, as set out in clause 6 and the interest thereon, towards the payment of the costs to repair any damage and / or lost keys to the Premises.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.7</span> <span class="corex-clause-text"><strong>The Lessee agrees to the new Lessee of the Premises being present at such outgoing in</strong><strong>spection with the Lessor</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.8</span> <span class="corex-clause-text"><strong>On expiry of the lease the Lessee shall hand over the keys of th</strong><strong>e premises to the Lessor</strong><strong> following the outgoing inspection by no later than 8 am on the day after the Termination date of the Lease Agreement unless otherwise agreed to in writing by the relevant parties.  Failure to do this</strong><strong> will entitle the Lessor </strong><strong>to deduct from the deposit any damages suffered as a result of any loss of rental income. </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.9</span> <span class="corex-clause-text"><strong>T</strong><strong>he Less</strong><strong>ee</strong><strong> undertakes to maintain at his own cost the whole of the Premises</strong><strong>, </strong>excluding <strong>the structure</strong><strong> a</strong><strong>nd roof of the house</strong><strong>,</strong><strong> for the full duration of the lease in the same state as they were received by</strong><strong> </strong><strong>him, reasonable fair wear and tear excepted, alternatively to reimburse the Lessor for the cost of replacing or repairing any breakages</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>S</strong><strong>hould the Lessee fail to maintain the Premises and/or goods in the manner specified in </strong><strong>t</strong><strong>his clause, the Lessor shall be entitled to carry out the necessary maintenance work at his</strong><strong> </strong><strong>discretion and to recover the f</strong><strong>ull cost thereof from the Lessee</strong><strong>.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text"><strong>O</strong><strong>n termination of the lease, the Lessee shall restore the whole of the Premises and the goods to the Lessor in the same good order and condition as they are at present, fair wear and tear excluded. The Lessor shall within 7 days after restoration of the Premises to him inspect the Premises and notify the Lessee in writing of all damages to or defects in the Premises for which the Lessee is liable in terms of </strong><strong>clause 13</strong><strong>.</strong></span></div>
<div class="corex-h1">14.  USE OF THE PREMISES BY THE LESSEE</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">14.1</span> <span class="corex-clause-text"><strong>1</strong><strong>4</strong><strong>.1</strong><strong>  </strong><strong>	</strong><strong>The Lessee shall use the Premises solely for residential purposes and hereby specifically undertakes not to contravene any law</strong><strong>,</strong><strong> bylaw, ordinance or regulation applicable in </strong><strong>r</strong><strong>espect of Premises in particular (if applicable) the rules applicable to the sectional title </strong><strong>s</strong><strong>cheme of which the Premises forms part.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">14.2</span> <span class="corex-clause-text"><strong>1</strong><strong>4</strong><strong>.</strong><strong>2</strong><strong>  </strong><strong>	</strong><strong>c</strong><strong>ause or permit any nuisance upon the Premises; or </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">14.3</span> <span class="corex-clause-text"><strong>1</strong><strong>4</strong><strong>.3</strong><strong>  </strong><strong>	</strong><strong>allow pets or other animals to damage the Premises; or</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">14.4</span> <span class="corex-clause-text"><strong>1</strong><strong>4</strong><strong>.4  </strong><strong>	</strong><strong>d</strong><strong>eface, mark, paint or drive nails, hooks or screws into the d</strong><strong>oors, walls, ceilings or floors</strong><strong> o</strong><strong>f the Premises, or place or display advertisements or notices of whatever nature on any part of the Premises, without the written consent of the Lessor; or keep any pets in or on the Premises without the Lessors’ prior written consent. </strong></span></div>
<div class="corex-h1">15.  IMPROVEMENTS</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>Any improvements made by the Lessee on or to the Premises during the period of the lease shall become the property of the Lessor on termination of the lease and the Lessee </strong><strong>s</strong><strong>hall not be entitled to remove any such improvement or claim from the Lessor any compensation in respect thereof.</strong><strong> The Lessor </strong><strong>shall be entitled at the </strong><strong>t</strong><strong>ermination of the lease to </strong><strong>d</strong><strong>emand in writing that any improvement or</strong><strong> </strong><strong>addition made by the Lessee be removed by the </strong><strong>L</strong><strong>essee at his own cost. The Lessee shall at his own expense and to the satisfaction of the Lessor repair a</strong><strong>ll damage and/or defects caused by such removal.</strong></span></div>
<div class="corex-h1">16.  BREACH</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">16.1</span> <span class="corex-clause-text"><strong>1</strong><strong>6</strong><strong>.1</strong><strong> </strong><strong> </strong><strong> </strong><strong>	</strong><strong>In the event of either one of the parties (the defaulting party) committing a breach of any of</strong><strong> </strong><strong>the terms</strong><strong> </strong><strong>of this Agreement and failing to remedy such breach within a period of 7 (seven) days after receipt</strong><strong> </strong><strong>of a written notice from the other party (“the aggrieved party”) calling upon the defaulting party to</strong><strong> </strong><strong>remedy the breach complained of, then the aggrieved party shall be entitled at his sole discretion and</strong><strong> </strong><strong>without prejudice to any rights in law and/or in terms of this Agreement, either to claim </strong><strong>s</strong><strong>pecific performance of the terms of this Agreement or to cancel this Agreement forthwith and without further notice and claim damages from the defaulting party.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">16.2</span> <span class="corex-clause-text"><strong>1</strong><strong>6</strong><strong>.2</strong><strong>  </strong><strong> </strong><strong>	</strong><strong>Provided that if the Lessee commits a breach of the provisions of this Agreement three times in any calendar year, then upon the third breach, the Lessor shall be entitled immediately to implement either of the remedies</strong><strong> </strong><strong>referred to above, without first having to give the Lessee written notice to rectify such breach.</strong><strong> </strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">16.3</span> <span class="corex-clause-text"><strong>1</strong><strong>6</strong><strong>.3</strong><strong>  </strong><strong>	</strong><strong>Should this Agreement be cancelled by the Lessor for any reason whatsoever, the Lessee </strong><strong>a</strong><strong>nd</strong><strong> </strong><strong>or </strong><strong>any</strong><strong> </strong><strong>o</strong><strong>ther </strong><strong>person</strong><strong> </strong><strong>occupying</strong><strong> the Premises on the Lessee’s behalf, shall immediately</strong><strong> </strong><strong>vacate the Premises and allow the Lessor to take occupation </strong><strong>thereof.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text"><strong>I</strong><strong>n the event of this Lease Agreement being cancelled during the fixed or any Renewal Periods of the</strong><strong> </strong><strong>Lease by the Lessee, a Lease cancellation fee amounting to 10% (Ten</strong><strong> percent) of the monthly rental </strong><strong>for the</strong><strong> remaining periods of the Lease is</strong><strong> payable</strong><strong> by the Lessee to the LANDLORD.</strong><strong> </strong><strong> </strong><strong>Payment of a Lease</strong><strong> cancellation fee does not constitute a </strong><strong>waiver of the LANDLORD’s righ</strong><strong>ts to institute a damaged claim</strong><strong> </strong><strong>in respect of a breach of th</strong><strong>is Lease Agreement by the Les</strong><strong>s</strong><strong>ee</strong><strong>.</strong><strong> </strong><strong> </strong><strong>It is agreed that this damages c</strong><strong>laim can be settled against the</strong><strong> damage deposit.</strong></span></div>
<div class="corex-h1">17. TERMINATION OF THE LEASE AGREEMENT</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text"><strong>The Lease agreement shall only be terminated when the Lessee vacates the premises and an out inspection has been done by the Agency.  The Lessee and Lessor hereby </strong><strong>agree</strong><strong> that no Private letting shall be allowed for as long as the Lessee is occupying the premises.</strong></span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text"><strong>Once the Lease Agreement has ended, the Lessor and / or Lessee may give the other party 20 business </strong><strong>days’ notice</strong><strong> of Termination of the Lease Agreement.</strong> </span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text"><strong>Should the Lessee cancel the Lease Agreement at any stage during the initial lease term as referred to in clause 5</strong><strong>, the Lessee will be held liable for the following cancellation costs to procure a new Lessee:</strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.3.1</span> <span class="corex-clause-text"><strong>The Lessee shall be held liable to pay the lease cancellation fee of </strong>R2000.00<strong> (Two Thousand Hundred</strong><strong> Rand)</strong><strong> for administration costs.</strong></span></div>
<div class="corex-h2">@include("docuperfect.web-templates.components.signature-line", ['party' => 'landlord'])
@include("docuperfect.web-templates.components.signature-line", ['party' => 'tenant'])
@include("docuperfect.web-templates.components.signature-line", ['party' => 'agent'])<br></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.3.2</span> <span class="corex-clause-text"><strong>The Lessee shall be held responsible for the monthly rental payments and advertising costs until such time as a new Lessee has been procured.</strong></span></div>
<div class="corex-h1">18. DOMICILE</div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.1</span> <span class="corex-clause-text"><strong>Each party choose </strong><strong>domicil</strong><strong>l</strong><strong>ium</strong><strong> </strong><strong>citandi</strong><strong> et </strong><strong>executandi</strong><strong> at his address as set out in 1 above, at which address all notices and legal process in relation to this Agreement or any action arising there from may be effectually delivered and serve</strong><strong>d.  </strong><strong>Any notice given by one of the parties to the other (“the addressee”) which – </strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">18.1.1</span> <span class="corex-clause-text"><strong>1</strong><strong>8</strong><strong>.</strong><strong>1.1</strong><strong> </strong><strong>	</strong><strong>I</strong><strong>s delivered by hand to the addressee’s </strong><strong>domicilium</strong><strong> </strong><strong>citandi</strong><strong> et </strong><strong>executandi</strong><strong> shall</strong><strong> </strong><strong>be presumed until the </strong><strong>contrary is proved to have been received by the</strong><strong> </strong><strong>addressee on the date of delivery; or</strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.2</span> <span class="corex-clause-text"><strong>Is posted by prepaid registered post from an address within the Republic of  South Africa to the addressee at the addressee’s </strong><strong>domicilium</strong><strong> </strong><strong>executandi</strong><strong> </strong><strong>shall be presumed until the contrary is proved to have been received by</strong><strong> </strong><strong>the addressee on the fifth day of the date of posting.</strong></span></div>
<div class="corex-clause corex-clause-indent-3"><span class="corex-clause-number">1.1.3</span> <span class="corex-clause-text"><strong>Is emailed with a delivery response to the email address as detailed in this agreement shall </strong><strong>b</strong><strong>e presumed until the contrary is proved to have been received by the addressee on the date</strong><strong> </strong><strong>of the delivery response.</strong></span></div>
<div class="corex-h1">19.  JURISDICTION</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><strong>The parties agree to the jurisdiction of the magistrate’s court in connection with any</strong><strong> </strong><strong>action or suit arising from this Agreement or the cancellation thereof.</strong><strong>  </strong><strong>Should two or more persons sign this Agreement as Lessors or Lessees, the said person shall be liable in solidum for the performance of the</strong><strong>ir obligations in terms of this a</strong><strong>greement.</strong><strong> </strong><strong>T</strong><strong>his Agreement constitutes the sole and entire agreement between the parties and no warranties, representations, guarantees or other terms and conditions of whatsoever nature</strong><strong> n</strong><strong>ot contained herein shall be of any force or effect.</strong></span></div>
<div class="corex-h1">20.  ESTATE AGENTS COMMISSION</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text">The Agency shall earn an ongoing commission equal to 10(Ten) percent, plus VAT of the monthly rental for the duration of the lease and any extension thereof.  (Please see Clause 17 on how a lease agreement shall be terminated).</span></div>
<div class="corex-h1">21.  SALE OF THE PROPERTY / LEASE OF PROPERTY NOT THROUGH HOME FINDERS COASTAL</div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.1</span> <span class="corex-clause-text">Should the Lessee or nominee enter into an agreement to purchase the property from the Lessor, the commission equal to 8.6% calculated on the selling price of the property, will be due to the Agency by the Lessor upon registration of such property.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.2</span> <span class="corex-clause-text">Should the Lessee or nominee enter into an agreement to lease the property privately, from the Lessor, the commission as calculated in clause 20, will be due to the Agency by the Lessor by the first of every month. (Please see Clause 17 on how a lease agreement shall be terminated).</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.3</span> <span class="corex-clause-text">Should the Lessor attempt sell or rent the property during the duration of this lease, it is agreed that Home Finders Coastal will have the Sole Mandate to market and / or rent the property.</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">1.4</span> <span class="corex-clause-text">The Lessee hereby confirms having been made aware that the Lessor may wish to sell the Property during the lease period and hereby undertakes to grant the agent access to the Property for this purpose provided that the requests for access are at reasonable times.</span></div>
<div class="corex-h1">22.PROTECTION OF PERSONAL INFORMATION</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The Landlord/s and the Tenant/s hereby give their consent to the estate agency/ies involved in the lease, to process our personal information for all purposes related to this lease, in accordance with the provisions of the Protection of Personal Information Act.  Such consent specifically includes the consent to work with and disclose our bank account details to facilitate the payment of the deposit and the monthly rent to the Landlord/s, and for the refund of the deposit to the Tenant/s.</span></div>
<div class="corex-h1">23.  OTHER CONDITIONS</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><span class="corex-field-value" data-field="other_conditions">{{ $other_conditions ?? '' }}</span></span></div>
<div class="corex-h2">@include("docuperfect.web-templates.components.signature-line", ['party' => 'landlord'])
@include("docuperfect.web-templates.components.signature-line", ['party' => 'tenant'])
@include("docuperfect.web-templates.components.signature-line", ['party' => 'agent'])<br></div>
<div class="corex-h2">Addendum A – Service Fee</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The parties hereby agree that the agent will be responsible for the following:</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">1.  Source a tenant	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">2.  Negotiate a rental contract 	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">3.  Secure deposit	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">4.  Secure first month’s rental	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">5.  Report on defects to the lessor	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">6.  Collect the monthly rental	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">7.  Ongoing liaison with the lessee	</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">8.      Collect the monthly Municipal/Eskom account from owner and pay over to the selected person.</span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The Agent shall earn an ongoing Service Fee equal to 10 %( plus vat) of the monthly rental for the duration of the lease and any extension thereof.</span></div>
<div class="corex-h2">Breakdown</div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Total Rental Amount 			<span class="corex-field-value" data-field="monthly_rental">{{ $monthly_rental ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Less Agent’s Service Fee (Including VAT)	<span class="corex-field-value" data-field="agent_fee_in_rands">{{ $agent_fee_in_rands ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Let’s Assist Fee				<span class="corex-field-value" data-field="lets_assists_fee">{{ $lets_assists_fee ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Net Amount to Owner			<span class="corex-field-value" data-field="owner_nett">{{ $owner_nett ?? '' }}</span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">               @include("docuperfect.web-templates.components.signature-line", ['party' => 'landlord'])
@include("docuperfect.web-templates.components.signature-line", ['party' => 'tenant'])
@include("docuperfect.web-templates.components.signature-line", ['party' => 'agent'])</span></div>

@include("docuperfect.web-templates.components.signature-block", ["parties" => ["Lessor", "Agent"]])

</div>
</div>

</body>
</html>
