<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMMOVABLE PROPERTY CONDITION REPORT IN RELATION TO THE SALE OF ANY IMMOVABLE PROPERTY (Property Practitioner Act 22 of 2019, Section 70 – Property Practitioners Regulations 2022 Section 36 – Mandatory Disclosure)</title>
    <link href="/css/corex-document.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
<div class="corex-document-wrapper">
<div class="corex-page">

@include("docuperfect.web-templates.components.company-header")

<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><u><strong>IMMOVABLE PROPERTY CONDITION REPORT IN RELATION TO THE SALE OF ANY IMMOVABLE PROPERTY</strong></u><u><strong> (Property Practitioner Act 22 of 2019, Section 70 – Property Practitioners Regulations 2022 Section 36 – Mandatory Disclosure)</strong></u></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">1</span> <span class="corex-clause-text"><strong>Disclaimer </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">This condition report concerns the immovable property situated at </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><span class="corex-field-value" style="border-bottom:1px solid #333; min-width:80pt; display:inline-block;">&nbsp;</span></span></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text"><em> </em>(the &quot;Property&quot;). This report does not constitute a guarantee or warranty of any kind by the owner of the Property or by the property practitioners representing that owner in any transaction. This report should, therefore, not be regarded as a substitute for any inspections or warranties that prospective purchasers may wish to obtain prior to concluding an agreement of sale in respect of the Property. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">2</span> <span class="corex-clause-text"><strong>Definitions </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">In this form –</span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">2.1</span> <span class="corex-clause-text">&quot;to be aware&quot; means to have actual notice or knowledge of a certain fact or state of affairs; and </span></div>
<div class="corex-clause corex-clause-indent-2"><span class="corex-clause-number">2.2</span> <span class="corex-clause-text">&quot;defect&quot; means any condition, whether latent or patent, that would or could have a significant deleterious or adverse impact on, or affect, the value of the property, that would or could significantly impair or impact upon the health or safety of any future occupants of the property or that, if not repaired, removed, or replaced, would or could significantly shorten or adversely affect the expected normal lifespan of the Property. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">3</span> <span class="corex-clause-text"><strong>Disclosure of information </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The owner of the Property discloses the information hereunder in the full knowledge that, even though this is not to be construed as a warranty, prospective purchasers of the Property may rely on such information when deciding whether, and on what terms, to purchase the Property. The owner hereby authorises the appointed property practitioner marketing the Property for sale to provide a copy of this statement, and to disclose any information contained in this statement, to any person in connection with any actual or anticipated sale of the Property. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">4</span> <span class="corex-clause-text"><strong>Provision of additional information </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The owner represents that to the best of his or her knowledge the responses to the statements in respect of the Property contained herein have been accurately noted as &quot;yes&quot;, &quot;no&quot; or &quot;not applicable&quot;. Should the owner have responded to any of the statements with a &quot;yes&quot;, the owner shall be obliged to provide, in the additional information area of this form, a full explanation as to the response to the statement concerned. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">5</span> <span class="corex-clause-text"><strong>Statements in connection with Property</strong></span></div>
<table class="corex-table"><thead><tr><th></th><th>YES</th><th>NO</th><th>N/A</th></tr></thead><tbody><tr><td>I am aware of the defects in the roof</td><td></td><td></td><td></td></tr><tr><td>I am aware of the defects in the electrical systems</td><td></td><td></td><td></td></tr><tr><td>I am aware of the defects in the plumbing system, including in the swimming pool (if any)</td><td></td><td></td><td></td></tr><tr><td>I am aware of the defects in the heating and air conditioning systems, including the air filters and humidifiers</td><td></td><td></td><td></td></tr><tr><td>I am aware of the defects in the septic or other sanitary disposal systems</td><td></td><td></td><td></td></tr><tr><td>I am aware of any defects to the property and/or in the basement or foundations of the property, including cracks, seepage and bulges. Other such defects include, but are not limited to, flooding, dampness or wet walls and unsafe concentrations of mould or defects in drain tiling or sump pumps</td><td></td><td></td><td></td></tr><tr><td>I am aware of structural defects in the Property</td><td></td><td></td><td></td></tr><tr><td>I am aware of boundary line dispute, encroachments, or encumbrances in connection with the Property</td><td></td><td></td><td></td></tr><tr><td>I am aware that remodelling and refurbishment have affected the structure of the Property</td><td></td><td></td><td></td></tr><tr><td>I am aware that any additions or improvements made to or any erections made on the property, have been done or were made, only after the required consents, permissions and permits to do so were properly obtained.</td><td></td><td></td><td></td></tr><tr><td>I am aware that a structure on the Property has been earmarked as a historic structure or heritage site</td><td></td><td></td><td></td></tr><tr><td></td></tr><tr><td>ADDITIONAL INFORMATION</td></tr><tr><td></td></tr><tr><td></td></tr><tr><td></td></tr><tr><td></td></tr><tr><td></td></tr></tbody></table><div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">6</span> <span class="corex-clause-text"><strong>Owner’s certification </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The owner hereby certifies that the information provided in this report is, to the best of the owner&#039;s knowledge and belief, true and correct as at the date when the owner signs this report. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">7</span> <span class="corex-clause-text"><strong>Certification by person supplying information </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">If a person other than the owner of the property provides the required information that person must certify that he/she is duly authorised by the owner to supply the information and that he/she has supplied the correct information on which the owner relied for the purposes of this report and, in addition, that the information contained herein is, to the best of that person&#039;s knowledge and belief, true and correct as at the date on which that person signs this report. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">8</span> <span class="corex-clause-text"><strong>Notice regarding advice or inspections </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">Both the owner as well as potential buyers of the property may wish to obtain professional advice and/or to undertake a professional inspection of the property. Under such circumstances adequate provisions must be contained in any agreement of sale to be concluded between the parties pertaining to the obtaining of any such professional advice and/or the conducting of required inspections and/or the disclosure of defects and/or the making of required warranties. </span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-number">9</span> <span class="corex-clause-text"><strong>Buyer’s acknowledgement </strong></span></div>
<div class="corex-clause corex-clause-indent-1"><span class="corex-clause-text">The prospective buyer acknowledges that he/she has been informed that professional expertise and/or technical skill and knowledge may be required to detect defects in, and non-compliant aspects concerning, the property. The prospective buyer acknowledges receipt of a copy of this statement. </span></div>
@include("docuperfect.web-templates.components.signature-line", ['party' => 'seller'])@include("docuperfect.web-templates.components.signature-line", ['party' => 'agent'])</div>

@include("docuperfect.web-templates.components.signature-block", ["parties" => ["Seller", "Agent", "Buyer"]])

</div>
</div>

</body>
</html>
