<?php

return [
    'crops' => [
        'macadamias' => [
            'label' => 'Macadamia Nuts',
            'lifespan_years' => 60,
            'years_to_first_crop' => 4,
            'years_to_peak' => 12,
            'peak_yield_tons_per_ha' => 3.5,
            'typical_trees_per_ha' => 312,
            'current_price_per_ton' => 6500000,
            'cost_per_ha' => 3500000,
            'yield_curve' => [1=>0,2=>0,3=>0,4=>5,5=>15,6=>25,7=>40,8=>55,9=>65,10=>75,11=>85,12=>95,13=>100,15=>100,40=>100,45=>90,50=>75,55=>60,60=>40],
            'questions' => [
                ['id' => 'mac_tree_age', 'question' => 'What is the age of the oldest and youngest trees?', 'inputType' => 'text', 'placeholder' => 'e.g., Oldest: 18 years, Youngest: 5 years'],
                ['id' => 'mac_current_yield', 'question' => 'What is the current yield per hectare?', 'inputType' => 'number', 'unit' => 't/ha', 'placeholder' => 'e.g., 3.2'],
                ['id' => 'mac_disease', 'question' => 'Are there any disease issues (e.g., nut borer, Phytophthora)?', 'inputType' => 'textarea', 'placeholder' => 'e.g., Nut borer present in Block 3, treated with...'],
                ['id' => 'mac_irrigation', 'question' => 'What irrigation system is in place?', 'inputType' => 'select', 'options' => ['None / Dryland', 'Drip', 'Micro-sprinkler', 'Overhead sprinkler', 'Flood/Furrow', 'Centre pivot']],
                ['id' => 'mac_rootstock', 'question' => 'What rootstock and cultivar are planted?', 'inputType' => 'text', 'placeholder' => 'e.g., Beaumont rootstock, 816 and 788 cultivars'],
                ['id' => 'mac_pruning', 'question' => 'When were trees last pruned or hedged?', 'inputType' => 'text', 'placeholder' => 'e.g., Hedged June 2025'],
                ['id' => 'mac_contracts', 'question' => 'Are there any processing/offtake contracts?', 'inputType' => 'textarea', 'placeholder' => 'e.g., 5-year contract with Green Farms Nut Co, expires 2027'],
                ['id' => 'mac_organic', 'question' => 'Is the orchard certified organic or GlobalGAP?', 'inputType' => 'boolean'],
                ['id' => 'mac_spacing', 'question' => 'What is the tree spacing?', 'inputType' => 'text', 'placeholder' => 'e.g., 8m x 4m'],
                ['id' => 'mac_replanting', 'question' => 'Are any blocks due for replanting?', 'inputType' => 'textarea'],
            ],
        ],
        'bananas' => [
            'label' => 'Bananas',
            'lifespan_years' => 25,
            'years_to_first_crop' => 1,
            'years_to_peak' => 3,
            'peak_yield_tons_per_ha' => 50,
            'typical_trees_per_ha' => 1800,
            'current_price_per_ton' => 550000,
            'cost_per_ha' => 8000000,
            'yield_curve' => [1=>40,2=>70,3=>100,5=>100,10=>95,15=>85,20=>70,25=>50],
            'questions' => [
                ['id' => 'ban_variety', 'question' => 'What banana varieties are planted?', 'inputType' => 'text', 'placeholder' => 'e.g., Williams, Grand Nain'],
                ['id' => 'ban_cycle', 'question' => 'What is the current ratoon cycle?', 'inputType' => 'text'],
                ['id' => 'ban_yield', 'question' => 'What is the current yield per hectare?', 'inputType' => 'number', 'unit' => 't/ha'],
                ['id' => 'ban_irrigation', 'question' => 'What irrigation system?', 'inputType' => 'select', 'options' => ['None / Dryland', 'Drip', 'Micro-sprinkler', 'Overhead', 'Flood/Furrow']],
                ['id' => 'ban_wind', 'question' => 'What wind protection is in place?', 'inputType' => 'text', 'placeholder' => 'e.g., Cavendish windbreaks'],
                ['id' => 'ban_disease', 'question' => 'Any disease issues (Panama disease, bunchy top)?', 'inputType' => 'textarea'],
                ['id' => 'ban_packhouse', 'question' => 'Is there an on-farm pack house?', 'inputType' => 'boolean'],
                ['id' => 'ban_market', 'question' => 'Primary market channel?', 'inputType' => 'select', 'options' => ['Fresh market', 'Processing', 'Export', 'Mixed']],
                ['id' => 'ban_nematode', 'question' => 'What nematode management is in place?', 'inputType' => 'textarea'],
            ],
        ],
        'sugar_cane' => [
            'label' => 'Sugar Cane',
            'lifespan_years' => 8,
            'years_to_first_crop' => 1,
            'years_to_peak' => 2,
            'peak_yield_tons_per_ha' => 80,
            'typical_trees_per_ha' => null,
            'current_price_per_ton' => 85000,
            'cost_per_ha' => 2500000,
            'yield_curve' => [1=>85,2=>100,3=>95,4=>90,5=>85,6=>75,7=>65,8=>55],
            'questions' => [
                ['id' => 'sug_varieties', 'question' => 'What cane varieties are planted?', 'inputType' => 'text', 'placeholder' => 'e.g., N12, N41'],
                ['id' => 'sug_ratoon', 'question' => 'What ratoon cycle are most fields on?', 'inputType' => 'text'],
                ['id' => 'sug_yield', 'question' => 'Current yield per hectare?', 'inputType' => 'number', 'unit' => 't/ha'],
                ['id' => 'sug_riv', 'question' => 'What is the RV (recoverable value) percentage?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'sug_irrigation', 'question' => 'Irrigation type?', 'inputType' => 'select', 'options' => ['Dryland', 'Drip', 'Centre pivot', 'Overhead', 'Flood/Furrow']],
                ['id' => 'sug_mill', 'question' => 'Which sugar mill?', 'inputType' => 'text', 'placeholder' => 'e.g., Tongaat Hulett - Maidstone'],
                ['id' => 'sug_quota', 'question' => 'What is the mill quota allocation?', 'inputType' => 'textarea'],
                ['id' => 'sug_haulage', 'question' => 'Distance to mill?', 'inputType' => 'text', 'unit' => 'km'],
                ['id' => 'sug_replanting', 'question' => 'Replanting schedule for next 3 years?', 'inputType' => 'textarea'],
                ['id' => 'sug_eldana', 'question' => 'Eldana borer status and management?', 'inputType' => 'textarea'],
            ],
        ],
        'litchis' => [
            'label' => 'Litchis',
            'lifespan_years' => 80,
            'years_to_first_crop' => 5,
            'years_to_peak' => 15,
            'peak_yield_tons_per_ha' => 10,
            'typical_trees_per_ha' => 200,
            'current_price_per_ton' => 2000000,
            'cost_per_ha' => 3000000,
            'yield_curve' => [5=>5,7=>20,10=>50,15=>100,20=>100,40=>100,60=>80,80=>50],
            'questions' => [
                ['id' => 'lit_tree_age', 'question' => 'Age of oldest and youngest trees?', 'inputType' => 'text'],
                ['id' => 'lit_variety', 'question' => 'What varieties?', 'inputType' => 'text', 'placeholder' => 'e.g., Mauritius, McLean\'s Red, HLH'],
                ['id' => 'lit_yield', 'question' => 'Current yield per hectare?', 'inputType' => 'number', 'unit' => 't/ha'],
                ['id' => 'lit_irrigation', 'question' => 'Irrigation system?', 'inputType' => 'select', 'options' => ['None / Dryland', 'Drip', 'Micro-sprinkler', 'Overhead']],
                ['id' => 'lit_alternate', 'question' => 'Is there alternate bearing? Pattern over last 3 years?', 'inputType' => 'textarea'],
                ['id' => 'lit_market', 'question' => 'Primary market?', 'inputType' => 'select', 'options' => ['Fresh local', 'Export', 'Processing', 'Mixed']],
                ['id' => 'lit_cold', 'question' => 'Is there cold chain / cold storage on farm?', 'inputType' => 'boolean'],
                ['id' => 'lit_pollination', 'question' => 'Any pollination issues?', 'inputType' => 'textarea'],
                ['id' => 'lit_disease', 'question' => 'Disease or pest issues (fruit borer, leaf miner)?', 'inputType' => 'textarea'],
            ],
        ],
        'avocados' => [
            'label' => 'Avocados',
            'lifespan_years' => 50,
            'years_to_first_crop' => 4,
            'years_to_peak' => 10,
            'peak_yield_tons_per_ha' => 12,
            'typical_trees_per_ha' => 400,
            'current_price_per_ton' => 2500000,
            'cost_per_ha' => 4500000,
            'yield_curve' => [4=>10,5=>20,6=>35,7=>50,8=>70,9=>85,10=>100,30=>100,40=>85,50=>60],
            'questions' => [
                ['id' => 'avo_tree_age', 'question' => 'Age of oldest and youngest trees?', 'inputType' => 'text'],
                ['id' => 'avo_variety', 'question' => 'What varieties?', 'inputType' => 'text', 'placeholder' => 'e.g., Hass, Fuerte, Ryan'],
                ['id' => 'avo_yield', 'question' => 'Current yield per hectare?', 'inputType' => 'number', 'unit' => 't/ha'],
                ['id' => 'avo_irrigation', 'question' => 'Irrigation system?', 'inputType' => 'select', 'options' => ['None / Dryland', 'Drip', 'Micro-sprinkler', 'Overhead']],
                ['id' => 'avo_rootstock', 'question' => 'What rootstock?', 'inputType' => 'text', 'placeholder' => 'e.g., Duke 7, Dusa'],
                ['id' => 'avo_export', 'question' => 'What percentage of crop goes to export?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'avo_packhouse', 'question' => 'Is there an on-farm pack house?', 'inputType' => 'boolean'],
                ['id' => 'avo_phytophthora', 'question' => 'Phytophthora root rot status and management?', 'inputType' => 'textarea'],
                ['id' => 'avo_alternate', 'question' => 'Alternate bearing pattern over last 3 years?', 'inputType' => 'textarea'],
                ['id' => 'avo_contracts', 'question' => 'Any export contracts or commitments?', 'inputType' => 'textarea'],
            ],
        ],
        'mangoes' => [
            'label' => 'Mangoes',
            'lifespan_years' => 40,
            'years_to_first_crop' => 4,
            'years_to_peak' => 10,
            'peak_yield_tons_per_ha' => 10,
            'typical_trees_per_ha' => 200,
            'current_price_per_ton' => 800000,
            'cost_per_ha' => 2500000,
            'yield_curve' => [4=>10,6=>30,8=>60,10=>100,20=>100,30=>85,40=>60],
            'questions' => [
                ['id' => 'man_variety', 'question' => 'What variety?', 'inputType' => 'text', 'placeholder' => 'e.g., Tommy Atkins, Kent, Keitt'],
                ['id' => 'man_tree_age', 'question' => 'How old are the trees?', 'inputType' => 'text'],
                ['id' => 'man_market', 'question' => 'Export or local market?', 'inputType' => 'select', 'options' => ['Fresh local', 'Export', 'Processing', 'Mixed']],
                ['id' => 'man_fruitfly', 'question' => 'Fruit fly management programme?', 'inputType' => 'textarea'],
            ],
        ],
        'citrus' => [
            'label' => 'Citrus',
            'lifespan_years' => 35,
            'years_to_first_crop' => 3,
            'years_to_peak' => 8,
            'peak_yield_tons_per_ha' => 40,
            'typical_trees_per_ha' => 500,
            'current_price_per_ton' => 600000,
            'cost_per_ha' => 5000000,
            'yield_curve' => [3=>10,4=>25,5=>40,6=>60,7=>80,8=>100,20=>100,25=>90,30=>75,35=>50],
            'questions' => [
                ['id' => 'cit_type', 'question' => 'What type?', 'inputType' => 'select', 'options' => ['Navel', 'Valencia', 'Lemon', 'Soft Citrus', 'Mixed']],
                ['id' => 'cit_tree_age', 'question' => 'How old are the orchards?', 'inputType' => 'text'],
                ['id' => 'cit_export', 'question' => 'Export-registered?', 'inputType' => 'boolean'],
                ['id' => 'cit_cbs', 'question' => 'CBS (Citrus Black Spot) status?', 'inputType' => 'textarea'],
                ['id' => 'cit_packhouse', 'question' => 'Packhouse on farm?', 'inputType' => 'boolean'],
                ['id' => 'cit_irrigation', 'question' => 'Irrigation type?', 'inputType' => 'select', 'options' => ['None / Dryland', 'Drip', 'Micro-sprinkler', 'Overhead']],
            ],
        ],
        'timber' => [
            'label' => 'Timber / Forestry',
            'lifespan_years' => 25,
            'years_to_first_crop' => 8,
            'years_to_peak' => 20,
            'peak_yield_tons_per_ha' => 250,
            'typical_trees_per_ha' => 1200,
            'current_price_per_ton' => 70000,
            'cost_per_ha' => 800000,
            'yield_curve' => [8=>10,12=>25,16=>50,20=>100],
            'questions' => [
                ['id' => 'tim_species', 'question' => 'What species?', 'inputType' => 'text', 'placeholder' => 'e.g., Eucalyptus grandis, Pine patula'],
                ['id' => 'tim_compartments', 'question' => 'Compartment breakdown with ages?', 'inputType' => 'textarea', 'placeholder' => 'List compartments with hectares and planting year'],
                ['id' => 'tim_rotation', 'question' => 'Expected rotation length?', 'inputType' => 'number', 'unit' => 'years'],
                ['id' => 'tim_volume', 'question' => 'Current standing volume estimate?', 'inputType' => 'number', 'unit' => 'm³'],
                ['id' => 'tim_market', 'question' => 'Primary market?', 'inputType' => 'select', 'options' => ['Pulp', 'Saw timber', 'Poles', 'Mining timber', 'Mixed']],
                ['id' => 'tim_fsc', 'question' => 'FSC certified?', 'inputType' => 'boolean'],
                ['id' => 'tim_fire', 'question' => 'Fire management — breaks, equipment, history?', 'inputType' => 'textarea'],
                ['id' => 'tim_roads', 'question' => 'Condition of extraction roads?', 'inputType' => 'textarea'],
                ['id' => 'tim_contracts', 'question' => 'Any supply contracts in place?', 'inputType' => 'textarea'],
            ],
        ],
        'vegetables' => [
            'label' => 'Vegetables / Market Garden',
            'lifespan_years' => 1,
            'years_to_first_crop' => 0,
            'years_to_peak' => 0,
            'peak_yield_tons_per_ha' => null,
            'typical_trees_per_ha' => null,
            'current_price_per_ton' => null,
            'cost_per_ha' => 10000000,
            'yield_curve' => [],
            'questions' => [
                ['id' => 'veg_crops', 'question' => 'What crops?', 'inputType' => 'text'],
                ['id' => 'veg_method', 'question' => 'Tunnel/greenhouse or open field?', 'inputType' => 'select', 'options' => ['Open field', 'Tunnel/Greenhouse', 'Mixed']],
                ['id' => 'veg_tunnels', 'question' => 'Number and size of tunnels?', 'inputType' => 'text'],
                ['id' => 'veg_irrigation', 'question' => 'Irrigation system?', 'inputType' => 'select', 'options' => ['None / Dryland', 'Drip', 'Micro-sprinkler', 'Overhead', 'Flood/Furrow']],
                ['id' => 'veg_market', 'question' => 'Market channel?', 'inputType' => 'select', 'options' => ['Fresh produce market', 'Retail', 'Informal', 'Mixed']],
                ['id' => 'veg_cold', 'question' => 'Cold storage on farm?', 'inputType' => 'boolean'],
            ],
        ],
        'other' => [
            'label' => 'Other Crop',
            'lifespan_years' => null,
            'years_to_first_crop' => null,
            'years_to_peak' => null,
            'peak_yield_tons_per_ha' => null,
            'typical_trees_per_ha' => null,
            'current_price_per_ton' => null,
            'cost_per_ha' => null,
            'yield_curve' => [],
            'questions' => [],
        ],
    ],
    'livestock' => [
        'cattle_beef' => [
            'label' => 'Beef Cattle',
            'value_per_head' => 1500000,
            'breeding_cow_value' => 2000000,
            'bull_value' => 4500000,
            'carrying_capacity_ha' => 4,
            'annual_revenue_per_head' => 800000,
            'annual_cost_per_head' => 350000,
            'questions' => [
                ['id' => 'beef_breed', 'question' => 'What breed?', 'inputType' => 'text', 'placeholder' => 'e.g., Brahman, Nguni, Bonsmara'],
                ['id' => 'beef_herd_size', 'question' => 'Total herd size?', 'inputType' => 'number', 'unit' => 'head'],
                ['id' => 'beef_carrying', 'question' => 'Carrying capacity of the farm?', 'inputType' => 'text', 'placeholder' => 'e.g., 1 LSU per 4 ha'],
                ['id' => 'beef_calving', 'question' => 'Current calving rate?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'beef_weaning', 'question' => 'Average weaning weight?', 'inputType' => 'number', 'unit' => 'kg'],
                ['id' => 'beef_market', 'question' => 'Primary market channel?', 'inputType' => 'select', 'options' => ['Weaners', 'Feedlot', 'Direct slaughter', 'Breeding stock', 'Auction']],
                ['id' => 'beef_supplementation', 'question' => 'What supplementary feeding is provided?', 'inputType' => 'textarea'],
                ['id' => 'beef_infrastructure', 'question' => 'Kraal, handling facilities, dip tank condition?', 'inputType' => 'textarea'],
                ['id' => 'beef_genetics', 'question' => 'Stud/breeding programme details?', 'inputType' => 'textarea'],
                ['id' => 'beef_vet', 'question' => 'Veterinary programme — vaccinations, dipping schedule?', 'inputType' => 'textarea'],
            ],
        ],
        'cattle_dairy' => [
            'label' => 'Dairy Cattle',
            'value_per_head' => 2500000,
            'breeding_cow_value' => 3000000,
            'annual_revenue_per_head' => 3500000,
            'annual_cost_per_head' => 2200000,
            'questions' => [
                ['id' => 'dairy_breed', 'question' => 'What breed?', 'inputType' => 'text', 'placeholder' => 'e.g., Holstein, Jersey, crossbreed'],
                ['id' => 'dairy_herd', 'question' => 'Total milking herd?', 'inputType' => 'number', 'unit' => 'cows'],
                ['id' => 'dairy_production', 'question' => 'Average litres per cow per day?', 'inputType' => 'number', 'unit' => 'litres'],
                ['id' => 'dairy_bulk', 'question' => 'Milk buyer?', 'inputType' => 'text', 'placeholder' => 'e.g., Clover, Woodlands, Fair Cape'],
                ['id' => 'dairy_parlour', 'question' => 'Parlour type and capacity?', 'inputType' => 'text', 'placeholder' => 'e.g., 20-point swing-over'],
                ['id' => 'dairy_cooling', 'question' => 'Bulk cooling tank on farm?', 'inputType' => 'boolean'],
                ['id' => 'dairy_pasture', 'question' => 'Pasture type and management?', 'inputType' => 'textarea'],
                ['id' => 'dairy_feed', 'question' => 'Feed programme — TMR, grazing, supplements?', 'inputType' => 'textarea'],
                ['id' => 'dairy_somatic', 'question' => 'Average somatic cell count?', 'inputType' => 'number', 'unit' => 'cells/ml'],
            ],
        ],
        'sheep' => [
            'label' => 'Sheep',
            'value_per_head' => 300000,
            'breeding_ewe_value' => 350000,
            'ram_value' => 1200000,
            'carrying_capacity_ha' => 1.5,
            'annual_revenue_per_head' => 250000,
            'annual_cost_per_head' => 120000,
            'questions' => [
                ['id' => 'sheep_breed', 'question' => 'What breed?', 'inputType' => 'text', 'placeholder' => 'e.g., Dorper, Merino, Dohne Merino'],
                ['id' => 'sheep_flock', 'question' => 'Total flock size?', 'inputType' => 'number', 'unit' => 'head'],
                ['id' => 'sheep_lambing', 'question' => 'Lambing percentage?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'sheep_purpose', 'question' => 'Primary purpose?', 'inputType' => 'select', 'options' => ['Meat', 'Wool', 'Dual purpose']],
                ['id' => 'sheep_shearing', 'question' => 'Wool clip per shearing?', 'inputType' => 'text', 'placeholder' => 'e.g., 4kg/sheep, twice annually'],
                ['id' => 'sheep_predation', 'question' => 'Predation issues and management?', 'inputType' => 'textarea'],
                ['id' => 'sheep_kraaling', 'question' => 'Night kraaling arrangements?', 'inputType' => 'textarea'],
            ],
        ],
        'goats' => [
            'label' => 'Goats',
            'value_per_head' => 250000,
            'annual_revenue_per_head' => 200000,
            'annual_cost_per_head' => 80000,
            'questions' => [
                ['id' => 'goat_breed', 'question' => 'What breed?', 'inputType' => 'text', 'placeholder' => 'e.g., Boer, Angora, Saanen, Indigenous'],
                ['id' => 'goat_herd', 'question' => 'Total herd size?', 'inputType' => 'number', 'unit' => 'head'],
                ['id' => 'goat_purpose', 'question' => 'Primary purpose?', 'inputType' => 'select', 'options' => ['Meat', 'Mohair', 'Milk', 'Breeding stock']],
                ['id' => 'goat_kidding', 'question' => 'Kidding rate?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'goat_browsing', 'question' => 'Browsing/grazing management?', 'inputType' => 'textarea'],
                ['id' => 'goat_predation', 'question' => 'Predation management?', 'inputType' => 'textarea'],
            ],
        ],
        'pigs' => [
            'label' => 'Pigs',
            'value_per_head' => 350000,
            'annual_revenue_per_head' => 500000,
            'annual_cost_per_head' => 300000,
            'questions' => [
                ['id' => 'pig_breed', 'question' => 'What breed?', 'inputType' => 'text', 'placeholder' => 'e.g., Large White, Landrace, Duroc'],
                ['id' => 'pig_sows', 'question' => 'How many sows?', 'inputType' => 'number', 'unit' => 'sows'],
                ['id' => 'pig_farrowing', 'question' => 'Farrowing rate?', 'inputType' => 'text'],
                ['id' => 'pig_housing', 'question' => 'Indoor or outdoor?', 'inputType' => 'select', 'options' => ['Indoor', 'Outdoor', 'Mixed']],
                ['id' => 'pig_contract', 'question' => 'Abattoir contract?', 'inputType' => 'textarea'],
            ],
        ],
        'poultry_broilers' => [
            'label' => 'Poultry — Broilers',
            'value_per_head' => 5000,
            'annual_cycles' => 6,
            'questions' => [
                ['id' => 'broiler_capacity', 'question' => 'House capacity?', 'inputType' => 'number', 'unit' => 'birds'],
                ['id' => 'broiler_houses', 'question' => 'Number of houses?', 'inputType' => 'number'],
                ['id' => 'broiler_cycles', 'question' => 'Cycles per year?', 'inputType' => 'number'],
                ['id' => 'broiler_contract', 'question' => 'Contract grower for?', 'inputType' => 'text', 'placeholder' => 'e.g., Astral, RCL, Country Bird'],
                ['id' => 'broiler_weight', 'question' => 'Average slaughter weight?', 'inputType' => 'number', 'unit' => 'kg'],
                ['id' => 'broiler_mortality', 'question' => 'Average mortality rate?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'broiler_ventilation', 'question' => 'House ventilation type?', 'inputType' => 'select', 'options' => ['Tunnel ventilated', 'Naturally ventilated', 'Climate controlled']],
                ['id' => 'broiler_generator', 'question' => 'Backup generator on site?', 'inputType' => 'boolean'],
            ],
        ],
        'poultry_layers' => [
            'label' => 'Poultry — Layers',
            'value_per_head' => 12000,
            'questions' => [
                ['id' => 'layer_capacity', 'question' => 'Total bird capacity?', 'inputType' => 'number', 'unit' => 'hens'],
                ['id' => 'layer_system', 'question' => 'Production system?', 'inputType' => 'select', 'options' => ['Free range', 'Barn', 'Cage', 'Enriched colony']],
                ['id' => 'layer_production', 'question' => 'Current lay rate?', 'inputType' => 'number', 'unit' => '%'],
                ['id' => 'layer_market', 'question' => 'Egg buyer?', 'inputType' => 'text', 'placeholder' => 'e.g., Eggs Inc, direct retail'],
                ['id' => 'layer_age', 'question' => 'Current flock age?', 'inputType' => 'text'],
                ['id' => 'layer_houses', 'question' => 'Number of houses?', 'inputType' => 'number'],
                ['id' => 'layer_grading', 'question' => 'On-farm egg grading facility?', 'inputType' => 'boolean'],
            ],
        ],
        'game' => [
            'label' => 'Game / Wildlife',
            'value_per_head' => null,
            'questions' => [
                ['id' => 'game_species', 'question' => 'What species and numbers?', 'inputType' => 'textarea', 'placeholder' => 'List all species with estimated numbers'],
                ['id' => 'game_exemption', 'question' => 'Do you have a game farm exemption certificate?', 'inputType' => 'boolean'],
                ['id' => 'game_fencing', 'question' => 'Fencing type and condition?', 'inputType' => 'textarea', 'placeholder' => 'e.g., 2.4m game fence, 2019, good condition'],
                ['id' => 'game_water', 'question' => 'Water points — boreholes, dams, troughs?', 'inputType' => 'textarea'],
                ['id' => 'game_hunting', 'question' => 'Hunting revenue — trophy, biltong, package hunts?', 'inputType' => 'textarea'],
                ['id' => 'game_breeding', 'question' => 'Any breeding projects? (e.g., sable, buffalo, roan)', 'inputType' => 'textarea'],
                ['id' => 'game_tourism', 'question' => 'Tourism/eco-tourism operations?', 'inputType' => 'textarea'],
                ['id' => 'game_vet', 'question' => 'Veterinary protocol and game capture arrangements?', 'inputType' => 'text'],
            ],
        ],
        'horses' => [
            'label' => 'Horses',
            'value_per_head' => 5000000,
            'questions' => [
                ['id' => 'horse_breed', 'question' => 'What breed?', 'inputType' => 'text', 'placeholder' => 'e.g., Thoroughbred, Boerperd, Warmblood'],
                ['id' => 'horse_purpose', 'question' => 'Stud or working horses?', 'inputType' => 'select', 'options' => ['Stud', 'Working', 'Sport', 'Mixed']],
                ['id' => 'horse_stabling', 'question' => 'Stabling capacity?', 'inputType' => 'text'],
                ['id' => 'horse_arena', 'question' => 'Arena or training facilities?', 'inputType' => 'textarea'],
            ],
        ],
        'other' => [
            'label' => 'Other Livestock',
            'value_per_head' => null,
            'questions' => [],
        ],
    ],
];
