{{-- DESIGN SYSTEM COMPLIANCE: UI_DESIGN_SYSTEM.md v 2026-04-20. --}}
{{--
    Phase D5 — Strategic weekly brief.

    Narrative comes from Anthropic Sonnet 4.6 via AnthropicGateway (handled
    by StrategicBriefService). $brief shape:
      narrative_text  string (AI or templated fallback — plain text)
      narrative_html  string (legacy templated HTML — kept for back-compat)
      generated_at    Carbon
      from_cache      bool
      from_fallback   bool   (true when API failed / disabled / capped)
      actions         array  (1-3 buttons routed back to Work tab)

    Spec: .ai/specs/mic-complete-spec.md §4.1.
--}}
@php
    $b = $brief ?? [
        'narrative_text' => '',
        'narrative_html' => '',
        'generated_at'   => null,
        'from_cache'     => false,
        'from_fallback'  => false,
        'actions'        => [],
    ];
    $generatedAt = $b['generated_at'] instanceof \Carbon\Carbon
        ? $b['generated_at']
        : ($b['generated_at'] ? \Carbon\Carbon::parse($b['generated_at']) : null);
    $narrative = $b['narrative_text'] ?? '';
    if ($narrative === '' && !empty($b['narrative_html'])) {
        // Legacy callers still passing HTML — strip tags so this view stays
        // in the plain-text branch.
        $narrative = trim(strip_tags($b['narrative_html']));
    }
    $sourceLabel = $b['from_fallback']
        ? 'fallback copy (AI unavailable)'
        : ($b['from_cache'] ? 'cached' : 'fresh');
@endphp

<div class="mi-card"
     style="background: linear-gradient(135deg, color-mix(in srgb, var(--brand-icon, #0ea5e9) 7%, var(--surface)) 0%, var(--surface) 70%);
            border: 1px solid color-mix(in srgb, var(--brand-icon, #0ea5e9) 25%, var(--border));">
    <div style="display: flex; align-items: flex-start; gap: 12px;">
        {{-- Ellie avatar --}}
        <div style="width: 36px; height: 36px; border-radius: 50%;
                    background: color-mix(in srgb, var(--brand-icon, #0ea5e9) 22%, transparent);
                    color: var(--brand-icon, #0ea5e9);
                    display: flex; align-items: center; justify-content: center;
                    font-weight: 700; flex-shrink: 0; font-size: 0.875rem;">
            E
        </div>

        <div style="flex: 1; min-width: 0;">
            <div style="display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; margin-bottom: 6px;">
                <span style="font-size: 0.625rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: var(--brand-icon, #0ea5e9);">
                    Weekly market brief
                </span>
                @if($b['from_fallback'])
                    <span style="font-size: 0.625rem; padding: 1px 6px; border-radius: 4px;
                                 background: color-mix(in srgb, var(--ds-amber, #f59e0b) 18%, transparent);
                                 color: var(--ds-amber, #d97706); font-weight: 600;">
                        Fallback
                    </span>
                @endif
            </div>

            <div style="font-size: 0.9375rem; color: var(--text-primary); line-height: 1.55; margin-bottom: 12px; white-space: pre-line;">{{ $narrative }}</div>

            @if(!empty($b['actions']))
            <div style="display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 10px;">
                @foreach($b['actions'] as $i => $action)
                    @php
                        $isPrimary = (bool) ($action['is_primary'] ?? ($i === 0));
                        $btnStyle = $isPrimary
                            ? 'background: var(--brand-icon, #0ea5e9); color: #fff; border: 1px solid var(--brand-icon, #0ea5e9);'
                            : 'background: var(--surface); color: var(--text-primary); border: 1px solid var(--border);';
                    @endphp
                    <a href="{{ $action['preset_url'] }}"
                       style="display: inline-flex; align-items: center; gap: 4px; padding: 6px 11px; font-size: 0.75rem; font-weight: 600; border-radius: 4px; text-decoration: none; {{ $btnStyle }}">
                        {{ $action['label'] }} →
                    </a>
                @endforeach
            </div>
            @endif

            {{-- Ellie footer — provenance + admin-only regenerate. --}}
            <div style="display: flex; align-items: center; justify-content: space-between;
                        padding-top: 8px; border-top: 1px solid color-mix(in srgb, var(--brand-icon, #0ea5e9) 18%, var(--border));
                        font-size: 0.625rem; color: var(--text-muted);">
                <span>
                    Generated by Ellie
                    @if($generatedAt) · {{ $generatedAt->diffForHumans() }} @endif
                    · {{ $sourceLabel }}
                </span>
                @permission('mic.regenerate_brief')
                    <form method="POST" action="{{ route('market-intelligence.brief.regenerate') }}" style="margin: 0;">
                        @csrf
                        <button type="submit"
                                style="background: none; border: 1px solid var(--border); border-radius: 6px;
                                       padding: 3px 8px; font-size: 0.625rem; color: var(--text-secondary);
                                       cursor: pointer;">
                            Regenerate
                        </button>
                    </form>
                @endpermission
            </div>
        </div>
    </div>
</div>
